import 'package:flutter/rendering.dart';

Color backgroundColor     = const Color(0xff261b2e);
Color watchColor          = const Color(0xffff8800);
Color secondsColor        = const Color(0xffff8800);
Color hoursColor          = const Color(0xffff8800);
Color hoursPointerColor   = const Color(0xffff8800);
Color minutesPointerColor = const Color(0xffff8800);
Color secondsPointerColor = const Color(0xffff8800);
Color labelColor          = const Color(0xff5e5eff);
Color centerDotColor      = const Color(0xff5e5eff);
Color textColor           = const Color(0xffff8800);
Color firstGradientColor  = const Color(0xff6b4a38);
Color secondGradientColor = const Color(0xff77533f);
Color thirdGradientColor  = const Color(0xff6b4a38);
Color hourCircleColor     = const Color(0xff59ffa9);
Color minuteCircleColor   = const Color(0xffff8800);
Color secondsCircleColor  = const Color(0xff5e5eff);
Color degreeTraceColor    = const Color(0xffff8800);
Color secondTraceColor    = const Color(0xffff8800);
Color hourTraceColor      = const Color(0xffff8800);
Color shadowColor         = const Color.fromRGBO(0, 0, 0, 0.7);